import { PageHero } from "@/components/PageHero";
import { ExternalLink } from "lucide-react";
export default function SB3670(){return <>
<PageHero dark kicker="Illinois · Health policy" title={"Catch Heart Disease Early Act."}><p className="mt-7 max-w-3xl text-xl leading-8 text-slate-300">Illinois Senate Bill 3670 would create a statewide framework for no-cost heart disease screenings, with screening frequency increasing at age 40.</p><div className="mt-7 flex flex-wrap gap-2 text-xs uppercase tracking-[.12em]"><span className="border border-white/30 px-3 py-2">SB 3670</span><span className="border border-white/30 px-3 py-2">Introduced Feb. 5, 2026</span><span className="border border-white/30 px-3 py-2">Illinois Senate</span></div></PageHero>
<section className="section"><div className="container-site grid gap-12 lg:grid-cols-[240px_minmax(0,720px)] lg:justify-center">
<aside className="text-sm text-muted"><div className="kicker">On this page</div><a href="#overview" className="block border-b border-line py-3">Overview</a><a href="#policy" className="block border-b border-line py-3">What the bill does</a><a href="#timeline" className="block border-b border-line py-3">Timeline</a><a href="#resources" className="block border-b border-line py-3">Resources</a></aside>
<article className="[&_h2]:serif [&_h2]:mt-14 [&_h2]:text-4xl [&_p]:mt-4 [&_p]:text-[1.05rem] [&_p]:leading-8 [&_p]:text-slate-700">
<h2 id="overview" className="!mt-0">Overview</h2><p>SB 3670, titled the <strong>Catch Heart Disease Early Act</strong>, was introduced in the Illinois Senate on February 5, 2026. The bill is sponsored by Sen. Adriane L. Johnson.</p>
<div className="my-8 border-l-4 border-blue bg-blue-50 p-5"><strong>North Star focus:</strong> making early heart-disease screening more accessible before cardiovascular problems become more severe, expensive, or difficult to treat.</div>
<h2 id="policy">What the bill does</h2><p>As introduced, the bill provides no-cost heart disease screenings for Illinois residents age 20 and older. The schedule is one screening every six years for adults ages 20–39 and one every two years for adults age 40 and older.</p><p>It removes patient cost-sharing for qualifying screenings and establishes the State of Illinois as payer of last resort for eligible uninsured or underinsured residents whose public or private coverage does not fully pay for screening.</p>
<h2 id="timeline">Legislative timeline</h2><div className="mt-6 border-l border-line pl-7"><div className="pb-8"><strong>February 5, 2026</strong><p className="!mt-1 !text-sm">Filed, first read, and referred to Assignments.</p></div><div className="pb-8"><strong>February 17, 2026</strong><p className="!mt-1 !text-sm">Assigned to Appropriations — Health and Human Services.</p></div><div><strong>May 22, 2026</strong><p className="!mt-1 !text-sm">Re-referred to Assignments under Senate Rule 3-9(a).</p></div></div>
<h2 id="resources">Official resources</h2><div className="mt-6 flex flex-wrap gap-3"><a className="btn" target="_blank" rel="noreferrer" href="https://my.ilga.gov/legislation/BillStatus?DocNum=3670&DocTypeID=SB&GAID=18&LegId=166854&SessionID=114">Bill status <ExternalLink size={15}/></a><a className="btn" target="_blank" rel="noreferrer" href="https://www.ilga.gov/documents/legislation/104/SB/PDF/10400SB3670.pdf">Introduced text <ExternalLink size={15}/></a></div>
</article></div></section>
</>}
